print (record.author())
print (record.isbn())
print (record.issn())
print (record.issn_title())
print (record.leader) 
print (record.location())
print ([x.value() for x in record.notes()])
print ([x.value() for x in record.physicaldescription()])
print (record.pos)
print (record.publisher())
print (record.pubyear())
print (record.series())
print ([x.value() for x in record.subjects()])
print (record.sudoc())
print (record.title())
print (record.uniformtitle())